#!/usr/bin/env python3
"""The one header navigation and speculation-rules block used by every page of the site.

    python web/scripts/site_nav.py           # rewrite the nav + speculation rules of every hand-written page
    python web/scripts/site_nav.py --check   # exit 1 if a page differs from what this script produces

Every page's `<header class="site">` gets the same `<nav class="site-nav">` (icon pills; the current
section carries aria-current="page"), and every page gets the same inline
`<script type="speculationrules">` before `</body>`. Guide pages are generated by build_guides.py,
which calls `normalize()` too; check_guides.py fails if any page differs from `normalize()`.
Redirect stubs (pages with a meta refresh) are left alone.

Labels are bilingual: one <span lang="vi"> and one <span lang="en">; site.css shows the one that
matches <html lang> (set by lang.js or contributor-ui.js), Vietnamese by default without JS.
"""
from __future__ import annotations

import pathlib
import re
import sys

WEB = pathlib.Path(__file__).resolve().parent.parent
PUBLIC = WEB / "public"

# 24×24 outline icons, stroke = currentColor (drawn for this site; no icon font, no CDN).
ICONS = {
    "book": '<path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20"/>',
    "list": '<path d="M9 6h12M9 12h12M9 18h8"/><path d="M4 6h.01M4 12h.01M4 18h.01"/><path d="m18 16 3 2-3 2z"/>',
    "heart-plus": '<path d="M12 20.5 4.6 13.2A4.9 4.9 0 0 1 12 6.8a4.9 4.9 0 0 1 7.4 6.4"/><path d="M18 15v6M15 18h6"/>',
    "shield": '<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><path d="m9 12 2 2 4-4"/>',
    "user-x": '<path d="M16 21v-2a4 4 0 0 0-4-4H7a4 4 0 0 0-4 4v2"/><circle cx="9.5" cy="7" r="4"/><path d="m17 8 5 5M22 8l-5 5"/>',
}

# (href, section prefix, icon, vi label, en label)
ITEMS = [
    ("/guides/", "/guides/", "book", "Hướng dẫn", "Guides"),
    ("/playlists/", "/playlists/", "list", "Danh sách cộng đồng", "Community playlists"),
    ("/contributor/", "/contributor/", "heart-plus", "Đóng góp", "Contribute"),
    ("/privacy/", "/privacy/", "shield", "Quyền riêng tư", "Privacy"),
    ("/delete-account/", "/delete-account/", "user-x", "Xoá tài khoản", "Delete account"),
]

SPECULATION_RULES = """<script type="speculationrules">
{"prefetch": [{"where": {"and": [
  {"href_matches": "/*"},
  {"not": {"selector_matches": "[href*='?'], [href*='#'], [href^='/contributor/admin'], [download]"}}
]}, "eagerness": "moderate"}]}
</script>"""


def nav_html(url_path: str) -> str:
    lines = ['    <nav class="site-nav" aria-label="Trang / Pages">']
    for href, prefix, icon, vi, en in ITEMS:
        current = ' aria-current="page"' if url_path.startswith(prefix) else ""
        lines.append(
            # Icon-only button; .nav-label is the accessible name and the hover/focus tooltip.
            f'      <a href="{href}"{current}>'
            f'<svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" stroke-width="1.9" '
            f'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">{ICONS[icon]}</svg>'
            f'<span class="nav-label"><span lang="vi">{vi}</span><span lang="en">{en}</span></span></a>'
        )
    lines.append("    </nav>")
    return "\n".join(lines)


HEADER_RE = re.compile(r'<header class="site">.*?</header>', re.S)
NAV_RE = re.compile(r"[ \t]*<nav\b.*?</nav>", re.S)
SIGNOUT_RE = re.compile(r'[ \t]*<button[^>]*id="signOut"[^>]*>.*?</button>\n?', re.S)
SPEC_RE = re.compile(r'<script type="speculationrules">.*?</script>\n?', re.S)


def url_path_of(path: pathlib.Path) -> str:
    rel = path.relative_to(PUBLIC).as_posix()
    return "/" + (rel[: -len("index.html")] if rel.endswith("index.html") else rel)


def is_redirect_stub(text: str) -> bool:
    return 'http-equiv="refresh"' in text


def normalize(text: str, url_path: str) -> str:
    """The page with the canonical nav and speculation rules (LF line endings)."""
    text = text.replace("\r\n", "\n")
    header_match = HEADER_RE.search(text)
    if not header_match:
        raise ValueError("no <header class=\"site\">")
    header = header_match.group(0)
    signout = ""
    m = SIGNOUT_RE.search(header)
    if m:   # contributor pages: the sign-out button stays in the header, after the nav
        signout = "    " + m.group(0).strip() + "\n"
        header = header[: m.start()] + header[m.end():]
    new_nav = nav_html(url_path)
    if NAV_RE.search(header):
        header = NAV_RE.sub(lambda _: new_nav, header, count=1)
    else:
        header = header.replace("\n  </div>\n</header>", "\n" + new_nav + "\n  </div>\n</header>", 1)
    header = header.replace("\n    </nav>\n", "\n    </nav>\n" + signout, 1)
    text = text[: header_match.start()] + header + text[header_match.end():]
    text = SPEC_RE.sub("", text)
    text = text.replace("</body>", SPECULATION_RULES + "\n</body>", 1)
    return text


def pages():
    for path in sorted(PUBLIC.rglob("*.html")):
        yield path


def main() -> int:
    check = "--check" in sys.argv[1:]
    bad = 0
    for path in pages():
        raw = path.read_bytes()
        text = raw.decode("utf-8")
        if is_redirect_stub(text):
            continue
        crlf = "\r\n" in text
        new = normalize(text, url_path_of(path))
        out = (new.replace("\n", "\r\n") if crlf else new).encode("utf-8")
        if out == raw:
            continue
        rel = path.relative_to(WEB.parent).as_posix()
        if check:
            print(f"differs: {rel}")
            bad += 1
        elif "/guides/" in "/" + path.relative_to(PUBLIC).as_posix():
            print(f"generated page, run build_guides.py: {rel}")
        else:
            path.write_bytes(out)
            print(f"wrote {rel}")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
